version: '3'

services:
  mongo:
    image: mongo

  nodetodos:
    image: nodetodo
    depends_on:
      - mongo
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - MONGODB_URL=mongodb://mongo:27017/todos
